
---

- name: install nginx
  hosts: nginx
  become: yes

  tasks:
  - name: install nginx
    ansible.builtin.apt:
      name: nginx
      state: present

  - name: copy config
    ansible.builtin.copy:
      src: ./data/my_nginx.conf
      dest: /etc/nginx/sites-available/my_nginx.conf
      force: yes
      backup: yes

  - name: copy cert
    ansible.builtin.copy:
      src: ./data/certs/nginx_cert.pem
      dest: /etc/ssl/certs/
      force: yes
      backup: yes

  - name: copy key
    ansible.builtin.copy:
      src: ./data/certs/nginx_key.pem
      dest: /etc/ssl/private/
      force: yes
      mode: '644'
      backup: yes

  - name: clean sites
    ansible.builtin.file:
      path: /etc/nginx/sites-enabled
      state: absent

  - name: create sites
    ansible.builtin.file:
      path: /etc/nginx/sites-enabled
      state: directory

  - name: create a symbolic link
    ansible.builtin.file:
      src: /etc/nginx/sites-available/my_nginx.conf
      dest: /etc/nginx/sites-enabled/my_nginx.conf
      force: yes
      state: link

  - name: copy html
    ansible.builtin.copy:
      src: ./data/index.html
      dest: /var/www/my_nginx/
      force: yes

  - name: start nginx
    ansible.builtin.service:
      name: nginx
      enabled: yes
      state: restarted
